// Code generated by goctl. DO NOT EDIT.
// Source: blockchain_service.proto

package server

import (
	"context"

	"github.com/JopenChen/star_guard/blockchain_service/rpc/blockchain"
	"github.com/JopenChen/star_guard/blockchain_service/rpc/internal/logic"
	"github.com/JopenChen/star_guard/blockchain_service/rpc/internal/svc"
)

type BlockchainServer struct {
	svcCtx *svc.ServiceContext
	blockchain.UnimplementedBlockchainServer
}

func NewBlockchainServer(svcCtx *svc.ServiceContext) *BlockchainServer {
	return &BlockchainServer{
		svcCtx: svcCtx,
	}
}

func (s *BlockchainServer) Create(ctx context.Context, in *blockchain.CreateDataRequest) (*blockchain.CreateDataResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *BlockchainServer) Retrieve(ctx context.Context, in *blockchain.RetrieveRequest) (*blockchain.RetrieveResponse, error) {
	l := logic.NewRetrieveLogic(ctx, s.svcCtx)
	return l.Retrieve(in)
}
